### ISSUE TITLE
Unexpected property: 'partitionKey'

### ISSUE THREAD

**Issue by powellnorma** [kairi003/Get-cookies.txt-LOCALLY#71]
For Chrome < 119, we get:
```
Uncaught (in promise) TypeError: Error in invocation of cookies.getAll(object details, function callback): Error at parameter 'details': Unexpected property: 'partitionKey'.
    at getAllCookies (get_all_cookies.mjs:9:71)
    at async updateBadgeCounter (background.mjs:17:19)
```

**Comment by kairi003** [comment]
thank you for your report!
